from curses import keyname
import pygame.locals


SCREEN_WIDTH = 1400
SCREEN_HEIGHT = 800


ARROW_COUNT_LEVEL_1 = 10
ARCHER_STARTING_POSITION = [20,20]
ARCHER_SHOOTING_ANIMATION_SPEED = 0.15
ARCHER_IDLE_ANIMATION_SPEED = 0.07
ARCHER_MOVING_SPEED = 7

BALLOON_SPEED = 1.7
BALLOON_ANIMATION_SPEED = 0.15
FIRST_BALLOON_DISTANCE = 600

ARROW_SPEED = 6.8

CLOCK = 60

MOVE_UP_KEY = pygame.K_UP
MOVE_DOWN_KEY = pygame.K_DOWN
SHOOT_KEY = pygame.K_SPACE


MENU_TITLE = ('Assets/menu/game_title_with_arrow.png')
MENU_SIZE_MULTIPLIER = 6.5
MENU_SIZE = (int(111*MENU_SIZE_MULTIPLIER),int(58*MENU_SIZE_MULTIPLIER))
PIXEL_FONT = ('Assets/font/pixel_font.ttf')
PLAY_BUTTON = ('Assets/menu/Play_button.png')
PLAY_BUTTON_RED = ('Assets/menu/Play_button_red.png')
PLAY_BUTTON_MULTIPLIER = 3.1
PLAY_BUTTON_SIZE = ((int(55*PLAY_BUTTON_MULTIPLIER), int(20*PLAY_BUTTON_MULTIPLIER)))
